// Paginas de categoria "folha" do Continente (HTML normal, nao-ajax) mapeadas para as
// 8 categorias suportadas. Cada URL e pedido uma unica vez (GET simples) e devolve ate
// 36 produtos renderizados no proprio HTML (ordenados pela regra de merchandising
// default do Continente, "Relevancia" / srule=Continente - nao e ordem de catalogo nem
// popularidade real, e curadoria do proprio Continente).
//
// Optamos deliberadamente por isto em vez do endpoint Search-UpdateGrid porque o
// robots.txt do Continente bloqueia os parametros usados por esse endpoint
// (?cgid=, ?start=, ?sz=, ?srule=). Estas paginas normais nao estao bloqueadas e
// estao listadas no sitemap de categorias do proprio site.
//
// Limitacao aceite: subcategorias com mais de 36 produtos perdem os restantes (sem
// paginacao disponivel de forma compatível com o robots.txt).

const MERCEARIA_URLS = [
  "https://www.continente.pt/mercearia/alimentacao-infantil/alimentos-lacteos/",
  "https://www.continente.pt/mercearia/alimentacao-infantil/boioes-saquetas-e-pure-de-fruta/",
  "https://www.continente.pt/mercearia/alimentacao-infantil/leites-em-po-e-bebidas-lacteas/",
  "https://www.continente.pt/mercearia/alimentacao-infantil/papas-infantis/",
  "https://www.continente.pt/mercearia/alimentacao-infantil/refeicoes/",
  "https://www.continente.pt/mercearia/alimentacao-infantil/snacks-e-bolachinhas/",
  "https://www.continente.pt/mercearia/arroz-massa-e-farinha/arroz/",
  "https://www.continente.pt/mercearia/arroz-massa-e-farinha/couscous-quinoa-bulgur-e-outros/",
  "https://www.continente.pt/mercearia/arroz-massa-e-farinha/farinhas/",
  "https://www.continente.pt/mercearia/arroz-massa-e-farinha/leguminosas/",
  "https://www.continente.pt/mercearia/arroz-massa-e-farinha/massa/",
  "https://www.continente.pt/mercearia/arroz-massa-e-farinha/noodles/",
  "https://www.continente.pt/mercearia/arroz-massa-e-farinha/pure/",
  "https://www.continente.pt/mercearia/azeite-oleo-e-vinagre/azeite/",
  "https://www.continente.pt/mercearia/azeite-oleo-e-vinagre/oleo/",
  "https://www.continente.pt/mercearia/azeite-oleo-e-vinagre/vinagre/",
  "https://www.continente.pt/mercearia/cafe-cha-e-bebidas-soluveis/bebidas-de-cereais/",
  "https://www.continente.pt/mercearia/cafe-cha-e-bebidas-soluveis/boutique-do-cafe/sistema-delta-q/",
  "https://www.continente.pt/mercearia/cafe-cha-e-bebidas-soluveis/boutique-do-cafe/sistema-dolce-gusto/",
  "https://www.continente.pt/mercearia/cafe-cha-e-bebidas-soluveis/boutique-do-cafe/sistema-nespresso/",
  "https://www.continente.pt/mercearia/cafe-cha-e-bebidas-soluveis/cafe-em-capsulas/",
  "https://www.continente.pt/mercearia/cafe-cha-e-bebidas-soluveis/cafe-soluvel/",
  "https://www.continente.pt/mercearia/cafe-cha-e-bebidas-soluveis/cafe-torrado/",
  "https://www.continente.pt/mercearia/cafe-cha-e-bebidas-soluveis/chas-e-infusoes/",
  "https://www.continente.pt/mercearia/cafe-cha-e-bebidas-soluveis/chocolate-soluvel/",
  "https://www.continente.pt/mercearia/conservas/atum/",
  "https://www.continente.pt/mercearia/conservas/cogumelos-milho-ervilhas/",
  "https://www.continente.pt/mercearia/conservas/feijao-e-grao-de-bico/",
  "https://www.continente.pt/mercearia/conservas/pates/",
  "https://www.continente.pt/mercearia/conservas/polpas-e-frutas-em-calda/",
  "https://www.continente.pt/mercearia/conservas/refeicoes/",
  "https://www.continente.pt/mercearia/conservas/salsichas/",
  "https://www.continente.pt/mercearia/conservas/sardinha-cavala-lulas/",
  "https://www.continente.pt/mercearia/conservas/tomate-polpa-pelado-e-seco/",
  "https://www.continente.pt/mercearia/molhos-temperos-e-sal/caldos/",
  "https://www.continente.pt/mercearia/molhos-temperos-e-sal/especiarias-e-ervas-aromaticas/",
  "https://www.continente.pt/mercearia/molhos-temperos-e-sal/maionese-ketchup-e-mostarda/",
  "https://www.continente.pt/mercearia/molhos-temperos-e-sal/molhos/",
  "https://www.continente.pt/mercearia/molhos-temperos-e-sal/preparados-de-sopas/",
  "https://www.continente.pt/mercearia/molhos-temperos-e-sal/sal/",
  "https://www.continente.pt/mercearia/sopas-e-refeicoes/refeicoes/",
  "https://www.continente.pt/mercearia/cabazes/",
];

const MERCEARIA_DOCE_SALGADA_URLS = [
  "https://www.continente.pt/mercearia/acucar-e-sobremesas/acucar-e-adocante/",
  "https://www.continente.pt/mercearia/acucar-e-sobremesas/aromas-e-toppings/",
  "https://www.continente.pt/mercearia/acucar-e-sobremesas/fermento/",
  "https://www.continente.pt/mercearia/acucar-e-sobremesas/gelatinas-e-pudins/",
  "https://www.continente.pt/mercearia/acucar-e-sobremesas/leite-condensado-e-leite-de-coco/",
  "https://www.continente.pt/mercearia/acucar-e-sobremesas/preparados-para-mousses-e-bolos/",
  "https://www.continente.pt/mercearia/batatas-fritas-e-aperitivos/batatas-fritas/",
  "https://www.continente.pt/mercearia/batatas-fritas-e-aperitivos/pipocas/",
  "https://www.continente.pt/mercearia/batatas-fritas-e-aperitivos/snacks-salgados/",
  "https://www.continente.pt/mercearia/bolachas-biscoitos-e-tostas/bolachas-com-cobertura-e-recheio/",
  "https://www.continente.pt/mercearia/bolachas-biscoitos-e-tostas/bolachas-de-chocolate/",
  "https://www.continente.pt/mercearia/bolachas-biscoitos-e-tostas/bolachas-de-manteiga/",
  "https://www.continente.pt/mercearia/bolachas-biscoitos-e-tostas/bolachas-e-biscoitos-salgados/",
  "https://www.continente.pt/mercearia/bolachas-biscoitos-e-tostas/bolachas-fibra-e-sem-acucar/",
  "https://www.continente.pt/mercearia/bolachas-biscoitos-e-tostas/bolachas-infantis/",
  "https://www.continente.pt/mercearia/bolachas-biscoitos-e-tostas/bolos-napolitanas-queques/",
  "https://www.continente.pt/mercearia/bolachas-biscoitos-e-tostas/maria-torrada-e-biscoitos/",
  "https://www.continente.pt/mercearia/bolachas-biscoitos-e-tostas/sortidos-de-bolachas/",
  "https://www.continente.pt/mercearia/bolachas-biscoitos-e-tostas/tortitas-de-arroz-e-milho/",
  "https://www.continente.pt/mercearia/bolachas-biscoitos-e-tostas/tostas-gressinos-e-croutons-2/",
  "https://www.continente.pt/mercearia/cereais-e-barras/barras-de-cereais/",
  "https://www.continente.pt/mercearia/cereais-e-barras/cereais-e-barras-infantis/",
  "https://www.continente.pt/mercearia/cereais-e-barras/cereais-infantis/",
  "https://www.continente.pt/mercearia/cereais-e-barras/cereais-linha-e-fibra/",
  "https://www.continente.pt/mercearia/cereais-e-barras/corn-flakes/",
  "https://www.continente.pt/mercearia/cereais-e-barras/flocos-e-papas-de-aveia/",
  "https://www.continente.pt/mercearia/cereais-e-barras/muesli-e-granola/",
  "https://www.continente.pt/mercearia/chocolate-gomas-e-rebucados/bombons/",
  "https://www.continente.pt/mercearia/chocolate-gomas-e-rebucados/chocolates/",
  "https://www.continente.pt/mercearia/chocolate-gomas-e-rebucados/chocolates-soluveis/",
  "https://www.continente.pt/mercearia/chocolate-gomas-e-rebucados/gomas-pastilhas-e-rebucados/",
  "https://www.continente.pt/mercearia/chocolate-gomas-e-rebucados/snacks-de-chocolate/",
  "https://www.continente.pt/mercearia/compotas-cremes-e-mel/doces-e-compotas/",
  "https://www.continente.pt/mercearia/compotas-cremes-e-mel/marmeladas-e-goiabadas/",
  "https://www.continente.pt/mercearia/compotas-cremes-e-mel/mel/",
  "https://www.continente.pt/mercearia/compotas-cremes-e-mel/nutella-e-cremes-de-barrar/",
];

const LATICINIOS_OVOS_URLS = [
  "https://www.continente.pt/laticinios-e-ovos/bebidas-vegetais-e-vegegurtes/bebida-amendoa/",
  "https://www.continente.pt/laticinios-e-ovos/bebidas-vegetais-e-vegegurtes/bebida-arroz/",
  "https://www.continente.pt/laticinios-e-ovos/bebidas-vegetais-e-vegegurtes/bebida-aveia/",
  "https://www.continente.pt/laticinios-e-ovos/bebidas-vegetais-e-vegegurtes/bebida-soja/",
  "https://www.continente.pt/laticinios-e-ovos/bebidas-vegetais-e-vegegurtes/vegegurtes/",
  "https://www.continente.pt/laticinios-e-ovos/gelatina-mousse-e-pudins/gelatina/",
  "https://www.continente.pt/laticinios-e-ovos/iogurtes-e-outros-lacteos/aromas-e-naturais/",
  "https://www.continente.pt/laticinios-e-ovos/iogurtes-e-outros-lacteos/bifidus/",
  "https://www.continente.pt/laticinios-e-ovos/iogurtes-e-outros-lacteos/gregos/",
  "https://www.continente.pt/laticinios-e-ovos/iogurtes-e-outros-lacteos/infantis/",
  "https://www.continente.pt/laticinios-e-ovos/iogurtes-e-outros-lacteos/kefir/",
  "https://www.continente.pt/laticinios-e-ovos/iogurtes-e-outros-lacteos/liquidos/",
  "https://www.continente.pt/laticinios-e-ovos/iogurtes-e-outros-lacteos/magros/",
  "https://www.continente.pt/laticinios-e-ovos/iogurtes-e-outros-lacteos/pedacos/",
  "https://www.continente.pt/laticinios-e-ovos/iogurtes-e-outros-lacteos/proteina/",
  "https://www.continente.pt/laticinios-e-ovos/iogurtes-e-outros-lacteos/sem-lactose/",
  "https://www.continente.pt/laticinios-e-ovos/iogurtes-e-outros-lacteos/vegegurtes/",
  "https://www.continente.pt/laticinios-e-ovos/laticinios-e-alternativas-vegetais/",
  "https://www.continente.pt/laticinios-e-ovos/leite/achocolatado-e-aromatizado/",
  "https://www.continente.pt/laticinios-e-ovos/leite/inteiro/",
  "https://www.continente.pt/laticinios-e-ovos/leite/magro/",
  "https://www.continente.pt/laticinios-e-ovos/leite/meio-gordo/",
  "https://www.continente.pt/laticinios-e-ovos/leite/po-e-bebidas-lacteas/",
  "https://www.continente.pt/laticinios-e-ovos/leite/sem-lactose/",
  "https://www.continente.pt/laticinios-e-ovos/manteigas-e-cremes-para-barrar/cremes-culinarios/",
  "https://www.continente.pt/laticinios-e-ovos/manteigas-e-cremes-para-barrar/cremes-para-barrar/",
  "https://www.continente.pt/laticinios-e-ovos/manteigas-e-cremes-para-barrar/manteigas/",
  "https://www.continente.pt/laticinios-e-ovos/natas-e-bechamel/cremes-vegetais/",
  "https://www.continente.pt/laticinios-e-ovos/natas-e-bechamel/molho-bechamel/",
  "https://www.continente.pt/laticinios-e-ovos/natas-e-bechamel/natas-culinarias/",
  "https://www.continente.pt/laticinios-e-ovos/natas-e-bechamel/natas-e-chantilly/",
  "https://www.continente.pt/laticinios-e-ovos/ovos/",
  "https://www.continente.pt/laticinios-e-ovos/queijos/",
  "https://www.continente.pt/frescos/queijos/amanteigado/",
  "https://www.continente.pt/frescos/queijos/curado/",
  "https://www.continente.pt/frescos/queijos/fatiado-e-bolas/",
  "https://www.continente.pt/frescos/queijos/fresco-e-requeijao/",
  "https://www.continente.pt/frescos/queijos/mozzarella-e-ricotta/",
  "https://www.continente.pt/frescos/queijos/queijos-do-mundo/",
  "https://www.continente.pt/frescos/queijos/ralado/",
  "https://www.continente.pt/frescos/queijos/snacks-e-barrar/",
  "https://www.continente.pt/frescos/queijos/tabuas-e-aperitivos/",
];

const TALHO_PEIXARIA_URLS = [
  "https://www.continente.pt/frescos/talho/cabrito-e-borrego/",
  "https://www.continente.pt/frescos/talho/frango-e-peru/frango/",
  "https://www.continente.pt/frescos/talho/frango-e-peru/peru/",
  "https://www.continente.pt/frescos/talho/novilho-vitela-e-vitelao/",
  "https://www.continente.pt/frescos/talho/pato-e-coelho/",
  "https://www.continente.pt/frescos/talho/porco/",
  "https://www.continente.pt/frescos/talho/pronto-a-cozinhar/",
  "https://www.continente.pt/frescos/peixaria/bacalhau/congelado/",
  "https://www.continente.pt/frescos/peixaria/bacalhau/fresco/",
  "https://www.continente.pt/frescos/peixaria/bacalhau/seco/",
  "https://www.continente.pt/frescos/peixaria/filetes-lombos-e-postas/congelado/",
  "https://www.continente.pt/frescos/peixaria/filetes-lombos-e-postas/fresco/",
  "https://www.continente.pt/frescos/peixaria/marisco/congelado/",
  "https://www.continente.pt/frescos/peixaria/marisco/fresco-e-cozido/",
  "https://www.continente.pt/frescos/peixaria/peixe-congelado/",
  "https://www.continente.pt/frescos/peixaria/peixe-fresco/",
  "https://www.continente.pt/frescos/peixaria/polvo-lulas-e-chocos/congelado/",
  "https://www.continente.pt/frescos/peixaria/polvo-lulas-e-chocos/fresco-e-cozido/",
  "https://www.continente.pt/frescos/peixaria/salmao-fumado-e-especialidades/",
];

const FRUTAS_LEGUMES_URLS = [
  "https://www.continente.pt/frescos/frutas/banana-maca-e-pera/",
  "https://www.continente.pt/frescos/frutas/cabazes-de-frutas-e-legumes/",
  "https://www.continente.pt/frescos/frutas/frutas-da-epoca/",
  "https://www.continente.pt/frescos/frutas/frutos-secos-desidratados-e-sementes/frutos-desidratados/",
  "https://www.continente.pt/frescos/frutas/frutos-secos-desidratados-e-sementes/frutos-secos/",
  "https://www.continente.pt/frescos/frutas/frutos-secos-desidratados-e-sementes/sementes-e-pevides/",
  "https://www.continente.pt/frescos/frutas/laranja-clementina-e-limao/",
  "https://www.continente.pt/frescos/frutas/melancia-melao-e-meloa/",
  "https://www.continente.pt/frescos/frutas/morango-e-frutos-vermelhos/",
  "https://www.continente.pt/frescos/frutas/pessego-ameixa-e-kiwi/",
  "https://www.continente.pt/frescos/frutas/sumos-espremidos-na-hora/",
  "https://www.continente.pt/frescos/frutas/uvas-e-tropicais/",
  "https://www.continente.pt/frescos/legumes/alface-tomate-pepino-e-pimento/",
  "https://www.continente.pt/frescos/legumes/batata-batata-doce-e-mandioca/",
  "https://www.continente.pt/frescos/legumes/cabazes-de-frutas-e-legumes/",
  "https://www.continente.pt/frescos/legumes/cebola-alho-e-nabo/",
  "https://www.continente.pt/frescos/legumes/cenoura-abobora-e-beterraba/",
  "https://www.continente.pt/frescos/legumes/cogumelos-espargos-e-exoticos/",
  "https://www.continente.pt/frescos/legumes/couves-brocolos-e-espinafres/",
  "https://www.continente.pt/frescos/legumes/curgete-beringela-e-feijao-verde/",
  "https://www.continente.pt/frescos/legumes/ervas-aromaticas-e-especiarias/",
  "https://www.continente.pt/frescos/legumes/saladas-sopas-e-salteados/",
  "https://www.continente.pt/frescos/legumes/tremocos-e-azeitonas/",
];

const PADARIA_PASTELARIA_URLS = [
  "https://www.continente.pt/frescos/padaria-e-pastelaria/biscoitos/",
  "https://www.continente.pt/frescos/padaria-e-pastelaria/bolas-de-berlim/",
  "https://www.continente.pt/frescos/padaria-e-pastelaria/bolos-e-sobremesas/",
  "https://www.continente.pt/frescos/padaria-e-pastelaria/croissants-e-paes-de-leite/",
  "https://www.continente.pt/frescos/padaria-e-pastelaria/massas-para-culinaria/",
  "https://www.continente.pt/frescos/padaria-e-pastelaria/pao-de-forma-e-embalado/",
  "https://www.continente.pt/frescos/padaria-e-pastelaria/pao-de-hamburguer-e-cachorro/",
  "https://www.continente.pt/frescos/padaria-e-pastelaria/pao-do-dia-e-broa/",
  "https://www.continente.pt/frescos/padaria-e-pastelaria/pastelaria-sortida/dunkin/",
  "https://www.continente.pt/frescos/padaria-e-pastelaria/tostas-e-gressinos/",
  "https://www.continente.pt/frescos/padaria-e-pastelaria/wraps-e-tortilhas/",
];

const CONGELADOS_URLS = [
  "https://www.continente.pt/congelados/batata-frita-e-pure/",
  "https://www.continente.pt/congelados/congelados-para-air-fryer/",
  "https://www.continente.pt/congelados/crocantes-e-hamburgueres/",
  "https://www.continente.pt/congelados/douradinhos-e-filetes/",
  "https://www.continente.pt/congelados/frutas-e-legumes/frutas/",
  "https://www.continente.pt/congelados/frutas-e-legumes/legumes/",
  "https://www.continente.pt/congelados/frutas-e-legumes/misturas-de-legumes/",
  "https://www.continente.pt/congelados/gelados/gelados-americanos/",
  "https://www.continente.pt/congelados/gelados/gelados-de-cone/",
  "https://www.continente.pt/congelados/gelados/gelados-de-pauzinho/",
  "https://www.continente.pt/congelados/gelados/gelados-familiares/",
  "https://www.continente.pt/congelados/gelados/gelados-infantis/",
  "https://www.continente.pt/congelados/gelados/gelados-vegan/",
  "https://www.continente.pt/congelados/gelados/mini-bites-e-sandwich/",
  "https://www.continente.pt/congelados/gelados-e-sobremesas-congeladas/",
  "https://www.continente.pt/congelados/hamburgueres-e-almondegas/",
  "https://www.continente.pt/congelados/nuggets-e-crocantes/",
  "https://www.continente.pt/congelados/pizzas/",
  "https://www.continente.pt/congelados/refeicoes-congeladas-1/",
  "https://www.continente.pt/congelados/refeicoes-prontas/carne/",
  "https://www.continente.pt/congelados/refeicoes-prontas/massas-e-gnocchis/",
  "https://www.continente.pt/congelados/refeicoes-prontas/peixe/",
  "https://www.continente.pt/congelados/refeicoes-prontas/salteados-e-sopas/",
  "https://www.continente.pt/congelados/salgados-folhados-e-pastelaria/folhados/",
  "https://www.continente.pt/congelados/salgados-folhados-e-pastelaria/pao-de-alho-e-pao-de-queijo/",
  "https://www.continente.pt/congelados/salgados-folhados-e-pastelaria/pastelaria-doce/",
  "https://www.continente.pt/congelados/salgados-folhados-e-pastelaria/salgados/",
  "https://www.continente.pt/congelados/sobremesas/bolos-congelados/",
  "https://www.continente.pt/congelados/sobremesas/crepes-e-petit-gateau/",
  "https://www.continente.pt/congelados/vegetariano-e-vegan/hamburgueres-e-almondegas/",
  "https://www.continente.pt/congelados/vegetariano-e-vegan/nuggets-e-panados/",
  "https://www.continente.pt/congelados/vegetariano-e-vegan/refeicoes-pizzas-e-falafel/",
];

const BEBIDAS_URLS = [
  "https://www.continente.pt/bebidas-e-garrafeira/0.0--alcool/",
  "https://www.continente.pt/bebidas-e-garrafeira/agua/agua-com-gas/",
  "https://www.continente.pt/bebidas-e-garrafeira/agua/agua-com-sabor/",
  "https://www.continente.pt/bebidas-e-garrafeira/agua/agua-sem-gas/",
  "https://www.continente.pt/bebidas-e-garrafeira/agua/agua-tonica-e-ginger-ale/",
  "https://www.continente.pt/bebidas-e-garrafeira/bebidas-energeticas-e-isotonicas/",
  "https://www.continente.pt/bebidas-e-garrafeira/bebidas-espirituosas/aguardente/",
  "https://www.continente.pt/bebidas-e-garrafeira/bebidas-espirituosas/aperitivos/",
  "https://www.continente.pt/bebidas-e-garrafeira/bebidas-espirituosas/brandy-conhaque-e-cachaca/",
  "https://www.continente.pt/bebidas-e-garrafeira/bebidas-espirituosas/cocktails/",
  "https://www.continente.pt/bebidas-e-garrafeira/bebidas-espirituosas/gin/",
  "https://www.continente.pt/bebidas-e-garrafeira/bebidas-espirituosas/licores/",
  "https://www.continente.pt/bebidas-e-garrafeira/bebidas-espirituosas/rum/",
  "https://www.continente.pt/bebidas-e-garrafeira/bebidas-espirituosas/tequila/",
  "https://www.continente.pt/bebidas-e-garrafeira/bebidas-espirituosas/vodka/",
  "https://www.continente.pt/bebidas-e-garrafeira/bebidas-espirituosas/whisky/",
  "https://www.continente.pt/bebidas-e-garrafeira/cervejas-e-sidras/cerveja-estrangeira-e-artesanal/",
  "https://www.continente.pt/bebidas-e-garrafeira/cervejas-e-sidras/cerveja-sem-alcool/",
  "https://www.continente.pt/bebidas-e-garrafeira/cervejas-e-sidras/cerveja-tradicional/",
  "https://www.continente.pt/bebidas-e-garrafeira/champanhe-e-espumante/champanhe/",
  "https://www.continente.pt/bebidas-e-garrafeira/champanhe-e-espumante/espumante/",
  "https://www.continente.pt/bebidas-e-garrafeira/gama-cave/",
  "https://www.continente.pt/bebidas-e-garrafeira/garrafeira/champanhe-e-espumante/",
  "https://www.continente.pt/bebidas-e-garrafeira/garrafeira/conjuntos-de-vinhos/",
  "https://www.continente.pt/bebidas-e-garrafeira/garrafeira/espirituosas/",
  "https://www.continente.pt/bebidas-e-garrafeira/garrafeira/vinho-do-porto-e-moscatel/",
  "https://www.continente.pt/bebidas-e-garrafeira/garrafeira/vinhos-premiados/",
  "https://www.continente.pt/bebidas-e-garrafeira/garrafeira-exclusiva-online/premiados/",
  "https://www.continente.pt/bebidas-e-garrafeira/garrafeira-vinhos-e-espirituosas/celebre-momentos-especiais/",
  "https://www.continente.pt/bebidas-e-garrafeira/garrafeira-vinhos-e-espirituosas/grandes-formatos/",
  "https://www.continente.pt/bebidas-e-garrafeira/garrafeira-vinhos-e-espirituosas/novidades/",
  "https://www.continente.pt/bebidas-e-garrafeira/garrafeira-vinhos-e-espirituosas/vinhos-biologicos/",
  "https://www.continente.pt/bebidas-e-garrafeira/sumos-e-refrigerantes/ice-tea-tisanas-e-kombuchas/",
  "https://www.continente.pt/bebidas-e-garrafeira/sumos-e-refrigerantes/nectares/",
  "https://www.continente.pt/bebidas-e-garrafeira/sumos-e-refrigerantes/refrigerantes-com-gas/",
  "https://www.continente.pt/bebidas-e-garrafeira/sumos-e-refrigerantes/refrigerantes-sem-gas/",
  "https://www.continente.pt/bebidas-e-garrafeira/sumos-e-refrigerantes/sumos-concentrados/",
  "https://www.continente.pt/bebidas-e-garrafeira/sumos-e-refrigerantes/sumos-de-fruta/",
  "https://www.continente.pt/bebidas-e-garrafeira/sumos-e-refrigerantes/sumos-infantis/",
  "https://www.continente.pt/bebidas-e-garrafeira/vinhos/sangrias-e-aromatizados/",
  "https://www.continente.pt/bebidas-e-garrafeira/vinhos/vinho-alentejo/",
  "https://www.continente.pt/bebidas-e-garrafeira/vinhos/vinho-branco/",
  "https://www.continente.pt/bebidas-e-garrafeira/vinhos/vinho-do-porto/vinho-do-porto-branco/",
  "https://www.continente.pt/bebidas-e-garrafeira/vinhos/vinho-do-porto/vinho-do-porto-por-colheita/",
  "https://www.continente.pt/bebidas-e-garrafeira/vinhos/vinho-do-porto/vinho-do-porto-ruby/",
  "https://www.continente.pt/bebidas-e-garrafeira/vinhos/vinho-do-porto/vinho-do-porto-tawny/",
  "https://www.continente.pt/bebidas-e-garrafeira/vinhos/vinho-do-porto/vinho-do-porto-vintage-lbv/",
  "https://www.continente.pt/bebidas-e-garrafeira/vinhos/vinho-moscatel-da-madeira-e-outros/vinho-da-madeira/",
  "https://www.continente.pt/bebidas-e-garrafeira/vinhos/vinho-moscatel-da-madeira-e-outros/vinho-moscatel-de-setubal/",
  "https://www.continente.pt/bebidas-e-garrafeira/vinhos/vinho-moscatel-da-madeira-e-outros/vinho-moscatel-do-douro/",
  "https://www.continente.pt/bebidas-e-garrafeira/vinhos/vinho-rose/",
  "https://www.continente.pt/bebidas-e-garrafeira/vinhos/vinhos-premiados/",
  "https://www.continente.pt/bebidas-e-garrafeira/vinhos/vinho-tinto/",
  "https://www.continente.pt/bebidas-e-garrafeira/vinhos/vinho-verde/",
];

// Subcategoria (e por vezes categoria, ex. cafe/cha e alimentacao infantil) derivada
// do proprio path da pagina de categoria do Continente - nunca do nome do produto.
// "mercearia" pura foi descontinuada (ver supabase/002_categories_and_subcategory.sql);
// tudo o que la estava agora cai em mercearia_doce_salgada, bebidas (cafe/cha) ou bebe
// (alimentacao infantil).
const URL_RULES = [
  { test: /\/cafe-cha-e-bebidas-soluveis\//, category: "bebidas", subcategory: "cafe_cha" },
  { test: /\/alimentacao-infantil\//, category: "bebe", subcategory: "cuidado_bebe" },

  { test: /\/arroz-massa-e-farinha\//, subcategory: "massas_arroz" },
  { test: /\/conservas\//, subcategory: "conservas" },
  { test: /\/azeite-oleo-e-vinagre\//, subcategory: "azeite_oleos" },
  { test: /\/molhos-temperos-e-sal\//, subcategory: "molhos_temperos" },
  { test: /\/sopas-e-refeicoes\//, subcategory: "molhos_temperos" },
  { test: /\/cabazes\//, subcategory: "massas_arroz" },
  { test: /\/acucar-e-sobremesas\//, subcategory: "compotas_mel" },
  { test: /\/batatas-fritas-e-aperitivos\//, subcategory: "snacks_aperitivos" },
  { test: /\/bolachas-biscoitos-e-tostas\//, subcategory: "bolachas_cereais" },
  { test: /\/cereais-e-barras\//, subcategory: "bolachas_cereais" },
  { test: /\/chocolate-gomas-e-rebucados\//, subcategory: "chocolates_doces" },
  { test: /\/compotas-cremes-e-mel\//, subcategory: "compotas_mel" },

  { test: /\/(laticinios-e-ovos|frescos)\/leite\//, subcategory: "leite" },
  { test: /\/iogurtes-e-outros-lacteos\//, subcategory: "iogurtes" },
  { test: /\/queijos\//, subcategory: "queijos" },
  { test: /\/manteigas-e-cremes-para-barrar\//, subcategory: "manteiga_natas" },
  { test: /\/natas-e-bechamel\//, subcategory: "manteiga_natas" },
  { test: /\/laticinios-e-ovos\/ovos\//, subcategory: "ovos" },
  { test: /\/gelatina-mousse-e-pudins\//, subcategory: "sobremesas_lacteas" },
  { test: /\/bebidas-vegetais-e-vegegurtes\//, subcategory: "bebidas_iogurtes_vegetais" },
  { test: /\/laticinios-e-alternativas-vegetais\//, subcategory: "bebidas_iogurtes_vegetais" },

  { test: /\/talho\/frango-e-peru\//, subcategory: "aves" },
  { test: /\/talho\/pato-e-coelho\//, subcategory: "aves" },
  { test: /\/talho\/porco\//, subcategory: "carne_porco" },
  { test: /\/talho\/(novilho-vitela-e-vitelao|cabrito-e-borrego)\//, subcategory: "carne_vaca" },
  { test: /\/talho\/pronto-a-cozinhar\//, subcategory: "charcutaria_enchidos" },
  { test: /\/peixaria\/marisco\//, subcategory: "marisco" },
  { test: /\/peixaria\/polvo-lulas-e-chocos\//, subcategory: "marisco" },
  { test: /\/peixaria\//, subcategory: "peixe_fresco" },

  { test: /\/frescos\/frutas\/frutos-secos-desidratados-e-sementes\//, subcategory: "frutos_secos" },
  { test: /\/frescos\/frutas\//, subcategory: "fruta" },
  { test: /\/frescos\/legumes\//, subcategory: "legumes" },

  { test: /\/padaria-e-pastelaria\/(pao-de-forma-e-embalado|pao-do-dia-e-broa|pao-de-hamburguer-e-cachorro|wraps-e-tortilhas)\//, subcategory: "pao" },
  { test: /\/padaria-e-pastelaria\/(bolos-e-sobremesas|pastelaria-sortida|bolas-de-berlim|massas-para-culinaria)\//, subcategory: "bolos_pastelaria" },
  { test: /\/padaria-e-pastelaria\/(biscoitos|tostas-e-gressinos)\//, subcategory: "torradas_tostas" },
  { test: /\/padaria-e-pastelaria\/croissants-e-paes-de-leite\//, subcategory: "croissants_folhados" },

  { test: /\/congelados\/gelados/, subcategory: "gelados" },
  { test: /\/congelados\/sobremesas\//, subcategory: "gelados" },
  { test: /\/congelados\/frutas-e-legumes\//, subcategory: "vegetais_congelados" },
  { test: /\/congelados\/batata-frita-e-pure\//, subcategory: "vegetais_congelados" },
  { test: /\/congelados\/douradinhos-e-filetes\//, subcategory: "peixe_marisco_congelado" },
  { test: /\/congelados\/(crocantes-e-hamburgueres|hamburgueres-e-almondegas|nuggets-e-crocantes|vegetariano-e-vegan)\//, subcategory: "carne_congelada" },
  { test: /\/congelados\/(pizzas|salgados-folhados-e-pastelaria)\//, subcategory: "massa_pizza_congelada" },
  { test: /\/congelados\/(refeicoes-prontas|refeicoes-congeladas|congelados-para-air-fryer)/, subcategory: "pratos_prontos_congelados" },

  { test: /\/bebidas-e-garrafeira\/agua\//, subcategory: "agua" },
  { test: /\/bebidas-e-garrafeira\/(sumos-e-refrigerantes|bebidas-energeticas-e-isotonicas)\//, subcategory: "refrigerantes_sumos" },
  { test: /\/bebidas-e-garrafeira\/(vinhos|champanhe-e-espumante|garrafeira|gama-cave)/, subcategory: "vinho" },
  { test: /\/bebidas-e-garrafeira\/cervejas-e-sidras\//, subcategory: "cerveja" },
  { test: /\/bebidas-e-garrafeira\/(bebidas-espirituosas|0\.0--alcool)\//, subcategory: "bebidas_espirituosas" },
];

function classify(url, defaultCategory) {
  for (const rule of URL_RULES) {
    if (rule.test.test(url)) {
      return { category: rule.category ?? defaultCategory, subcategory: rule.subcategory ?? null };
    }
  }
  return { category: defaultCategory, subcategory: null };
}

function build(urls, category) {
  return urls.map((url) => ({ url, ...classify(url, category) }));
}

export const CATEGORY_QUERIES = [
  ...build(MERCEARIA_URLS, "mercearia_doce_salgada"),
  ...build(MERCEARIA_DOCE_SALGADA_URLS, "mercearia_doce_salgada"),
  ...build(LATICINIOS_OVOS_URLS, "laticinios_ovos"),
  ...build(TALHO_PEIXARIA_URLS, "talho_peixaria"),
  ...build(FRUTAS_LEGUMES_URLS, "frutas_legumes"),
  ...build(PADARIA_PASTELARIA_URLS, "padaria_pastelaria"),
  ...build(CONGELADOS_URLS, "congelados"),
  ...build(BEBIDAS_URLS, "bebidas"),
];
